# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ceace5ae0634708f55842750019dc633fdb876d37ec1bdff6ae694da21165f7102a6711fad9cb7366feae783c422c2a3f9f1cddf29729ca6e064e2b0c03cbf5f

test:
  secret_key_base: 21acee284e9a8504ac658443b0464b86a4a8a6704041fc7852f19c4975cd957773ce03cddbde5437cf54ec344df557a0de065a8de29e3c93fec11ef9e7592f41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
